export const theme = {
  dark: {
    colors: {
      baseColor: '#151515',
      success: '#11af11',
      danger: '#9b1212',
      warning: '#cfdb1d',
      primary: '#370aa1',
      secondary: '#7492af',
      powderWhite: '#FFFDF9',
      persianGreen: '#06B49A',
      lightBlue: '#AFDBD2',
      onyx: '#36313D',
      green: 'green',
      mainGray: '#3b3b3b',
      title: '#fffff',
      text: '#fffff',
    },
    fonts: ['sans-serif', 'Roboto'],
    fontSizes: {
      small: '1em',
      medium: '2em',
      large: '3em',
    },
  },
  light: {
    colors: {
      baseColor: '#87d8d8',
      success: '#11af11',
      danger: '#9b1212',
      warning: '#cfdb1d',
      primary: '#370aa1',
      secondary: '#7492af',
      powderWhite: '#FFFDF9',
      persianGreen: '#06B49A',
      lightBlue: '#AFDBD2',
      onyx: '#36313D',
      green: 'green',
      title: '#10004b',
      text: '#190355',
    },
    fonts: ['sans-serif', 'Roboto'],
    fontSizes: {
      small: '1em',
      medium: '2em',
      large: '3em',
    },
  },
};
